# If name is not specified, the image name will be derived from the directory name. Which can lead to conflicts.
name: my-app

services:
  app:
    image: app # Custom image name
    build:
      context: ../ # Use the parent directory as the build context
      dockerfile: .docker/Dockerfile
    container_name: app
    ports:
      - "3000:80" # map port 80 in container (nginx) to 3000 in host machine
