name: CI
run-name: Validate PR from ${{ github.actor }}

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

env:
  NODE_VERSION: 22

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      # Cache TypeScript build info and ESLint cache for faster subsequent runs
      - name: Cache TypeScript and ESLint
        uses: actions/cache@v4
        with:
          path: |
            .eslintcache
          key: ts-eslint-cache-${{ runner.os }}-${{ hashFiles('**/*.ts', '**/*.tsx', 'eslint.config.mjs') }}
          restore-keys: |
            ts-eslint-cache-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      # Run type checking first as it's often the fastest way to catch issues
      - name: Type checking
        run: pnpm run typecheck

      # Run linting with cache
      - name: Run lint
        run: pnpm run lint
